feat: добавлена функция реквестов на вещи, добавлено тестирование мод…
PiFFFko/java-shareit pull request #3
Opened 2023-06-23 15:03 UTC by PiFFFko

feat: добавлена функция реквестов на вещи, добавлено тестирование модулей приложения

2023-06-26 15:59 UTC, andrew-larkin requested changes
Привет! Отлично, довольно качественная реализация нового функционала - много удачных решений, архитектура и код достаточно чистые. Требуется выполнить некоторый рефакторинг в контроллерах и сервисах + есть пара предложений, которые я рекомендую выполнить если позволяет время.

2023-06-26 15:59 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<Booking> getAllBookingsForBooker(Long userId, BookingState state, Long from, Long size);
всю доп логику по маппингу и другим манипуляцим из контроллеров стоит перенести в сервис (тогда контроллеры станут легковесными и будут выполнять единственную функцию по маршрутизации запросов от клиента - это соблюдение принципа S в аббревиатуре SOLID). Соответственно, в интерфейсах сервиса возвращаемым типом будет dto. Такой рефакторинг стоит провести со всеми контроллерами и сервисами

2023-06-26 15:59 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                    @RequestParam(defaultValue = "ALL", required = false) String state,
предлагаю внедрить новый класс-обертку для методов контроллера ResponseEntity - он возвращает не только json, но и http-статус, что довольно удобно. Будет выглядеть как-то так:
return ResponseEntity.ok().body(bookingService.getAllBookins..);
Для всех методов во всех контроллерах стоит его добавить

2023-06-26 15:59 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllByBookerId(Long userId, Pageable pageable);
над классом стоит добавить @Repository

2023-06-26 15:59 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +import ru.practicum.shareit.item.dto.*;
если есть время, предлагаю добавить в проект библиотеку mapStruct - она используется на всех реальных проектах, будет очень полезно ее изучить. Благодаря ней методы маппинга будут писаться в одну строчку

2023-06-26 15:59 UTC, andrew-larkin commented on src/main/resources/application.properties
> +#--- jdbc.driverClassName=org.postgresql.Driver
закомментированный код везде стоит удалить

2023-06-26 15:59 UTC, andrew-larkin commented on src/test/java/ru/practicum/shareit/booking/service/impl/BookingServiceImplTest.java
> +    ItemRepository itemRepository;
в тестах также стоит использовать модификаторы доступа для внедряемых сущностей и переменных

2023-06-27 11:17 UTC, PiFFFko commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<Booking> getAllBookingsForBooker(Long userId, BookingState state, Long from, Long size);
Дело в том, что на одном из предыдущих ТЗ изначально у меня преобразования были в сервисе, но ревьюер сказал, что необходимо вынести это в контроллер, что я тогда и сделал. 
![image](https://github.com/PiFFFko/java-shareit/assets/38191066/a5307a4c-7606-47cb-bd3c-c5c103a5a7f1)
Ссылка со скриншота: https://ru.stackoverflow.com/questions/1110180/Почему-репозиторий-не-должен-возвращать-dto
На следующем проекте изначально я бы тоже стал выполнять эти манипуляции в сервисе, ибо так удобнее, но перерефакторивать сейчас это же огромный пласт работы, который еще и заденет тесты. Можем оставить так?

2023-06-29 11:39 UTC, merged